services:
  postgres:
    image: postgres:17-alpine
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api-1:
    build:
      context: .
    command: ["/bin/api"]
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: local
      HTTP_PORT: 8080
      APP_BASE_URL: http://localhost:8080
      SHORT_CODE_LENGTH: 7
      SHORT_URL_CACHE_TTL: 24h
      SHORT_URL_NEGATIVE_CACHE_TTL: 1m
      DATABASE_URL: postgres://admin:adminpassword@postgres:5432/url_shortener?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      CLICK_STREAM_NAME: url_clicks
      CLICK_STREAM_GROUP: url_click_workers
      CLICK_STREAM_CONSUMER: api-unused
      CLICK_STREAM_BATCH_SIZE: 100
      CLICK_STREAM_BLOCK_TIME: 5s
      WORKER_METRICS_PORT: 9091
      RATE_LIMIT_ENABLED: "true"
      RATE_LIMIT_CREATE_LIMIT: 3
      RATE_LIMIT_CREATE_WINDOW: 1m
      RATE_LIMIT_RESOLVE_LIMIT: 5
      RATE_LIMIT_RESOLVE_WINDOW: 1m
      RATE_LIMIT_FAIL_OPEN: "true"

  api-2:
    build:
      context: .
    command: ["/bin/api"]
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: local
      HTTP_PORT: 8080
      APP_BASE_URL: http://localhost:8080
      SHORT_CODE_LENGTH: 7
      SHORT_URL_CACHE_TTL: 24h
      SHORT_URL_NEGATIVE_CACHE_TTL: 1m
      DATABASE_URL: postgres://admin:adminpassword@postgres:5432/url_shortener?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      CLICK_STREAM_NAME: url_clicks
      CLICK_STREAM_GROUP: url_click_workers
      CLICK_STREAM_CONSUMER: api-unused
      CLICK_STREAM_BATCH_SIZE: 100
      CLICK_STREAM_BLOCK_TIME: 5s
      WORKER_METRICS_PORT: 9091
      RATE_LIMIT_ENABLED: "true"
      RATE_LIMIT_CREATE_LIMIT: 3
      RATE_LIMIT_CREATE_WINDOW: 1m
      RATE_LIMIT_RESOLVE_LIMIT: 5
      RATE_LIMIT_RESOLVE_WINDOW: 1m
      RATE_LIMIT_FAIL_OPEN: "true"

  worker:
    build:
      context: .
    command: ["/bin/worker"]
    depends_on:
      - postgres
      - redis
    ports:
      - "9091:9091"
    environment:
      APP_ENV: local
      DATABASE_URL: postgres://admin:adminpassword@postgres:5432/url_shortener?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      CLICK_STREAM_NAME: url_clicks
      CLICK_STREAM_GROUP: url_click_workers
      CLICK_STREAM_CONSUMER: worker-1
      CLICK_STREAM_BATCH_SIZE: 100
      CLICK_STREAM_BLOCK_TIME: 5s
      WORKER_METRICS_PORT: 9091

  nginx:
    image: nginx:alpine
    depends_on:
      - api-1
      - api-2
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  prometheus:
    image: prom/prometheus
    container_name: url-shortener-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api-1
      - api-2
      - worker

  migrate:
    image: migrate/migrate
    profiles: ["tools"]
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://admin:adminpassword@postgres:5432/url_shortener?sslmode=disable",
        "up"
      ]

volumes:
  postgres_data:
  redis_data:
